name: Ryan Turner
markdown: redcarpet
highlighter: pygments
github: https://www.github.com/ryanturner
about: I am a software engineer from Memphis Tennessee who works mostly on mobile applications, webservices, and web design.
urls:
    - text: github
      url: https://github.com/liamsymonds
baseurl: '/'
